import type { CarbonCredit } from '@/lib/types';

export const placeholderCredits: CarbonCredit[] = [
  {
    id: 'proj-amazon-reforestation',
    sellerName: 'Florestas Renovadas Ltda.',
    creditType: 'Forestry',
    quantity: 5000,
    location: 'Amazonas, Brasil',
    pricePerCredit: 15.50,
    vintage: '2023',
    standard: 'Verra VCS',
    projectOverview: 'This project focuses on reforesting 10,000 hectares of the Amazon rainforest, previously affected by deforestation. It aims to restore biodiversity and create a sustainable ecosystem for local communities.',
    status: 'Ativo',
  },
  {
    id: 'proj-bahia-wind-farm',
    sellerName: 'Energia Eólica do Nordeste S.A.',
    creditType: 'Renewable Energy',
    quantity: 12000,
    location: 'Bahia, Brasil',
    pricePerCredit: 22.00,
    vintage: '2022',
    standard: 'Gold Standard',
    projectOverview: 'A large-scale wind farm generating over 200 GWh of clean energy annually, displacing fossil fuel-based power generation and reducing greenhouse gas emissions significantly.',
    status: 'Ativo',
  },
  {
    id: 'proj-sao-paulo-landfill',
    sellerName: 'Eco Gestão Ambiental',
    creditType: 'Waste Management',
    quantity: 3500,
    location: 'São Paulo, Brasil',
    pricePerCredit: 12.75,
    vintage: '2023',
    standard: 'CDM',
    projectOverview: 'Methane gas capture and electricity generation project at a major urban landfill. The project prevents the release of potent greenhouse gases and converts waste into a valuable energy resource.',
    status: 'Ativo',
  },
  {
    id: 'proj-mato-grosso-agriculture',
    sellerName: 'AgroSustentável',
    creditType: 'Agriculture',
    quantity: 8000,
    location: 'Mato Grosso, Brasil',
    pricePerCredit: 18.25,
    vintage: '2022',
    standard: 'Climate Action Reserve (CAR)',
    projectOverview: 'Implementation of sustainable agricultural practices, including no-till farming and cover cropping, to enhance soil carbon sequestration across thousands of hectares of farmland.',
    status: 'Pausado',
  },
  {
    id: 'proj-parana-solar',
    sellerName: 'Sol do Sul Energia',
    creditType: 'Renewable Energy',
    quantity: 15000,
    location: 'Paraná, Brasil',
    pricePerCredit: 25.00,
    vintage: '2024',
    standard: 'Gold Standard',
    projectOverview: 'A new-generation solar power plant with advanced tracking technology to maximize energy output. This project supplies clean power to the regional grid and promotes energy independence.',
    status: 'Ativo',
  },
    {
    id: 'proj-cerrado-conservation',
    sellerName: 'Guardiões do Cerrado',
    creditType: 'Forestry',
    quantity: 7500,
    location: 'Goiás, Brasil',
    pricePerCredit: 19.80,
    vintage: '2023',
    standard: 'Verra VCS',
    projectOverview: 'A conservation project aimed at protecting the unique biodiversity of the Cerrado biome from agricultural expansion. The project supports local communities with sustainable income alternatives.',
    status: 'Vendido',
  },
];
