// src/firebase/config.ts
// DO NOT EDIT - This file is automatically generated by Firebase Studio
export const firebaseConfig = {
  apiKey: "AIzaSyAFH8O36DKxdui3CClrJqkgEf_2YgsTOT0",
  authDomain: "pecus-intermediate.firebaseapp.com",
  databaseURL: "https://pecus-intermediate-default-rtdb.firebaseio.com",
  projectId: "pecus-intermediate",
  storageBucket: "pecus-intermediate.appspot.com",
  messagingSenderId: "667966942508",
  appId: "1:667966942508:web:df881058a5e69464175089",
};
